use std::fs;
use std::path::{Path, PathBuf};

fn generate_source_adapter_registry(manifest_dir: &Path) {
    let adapters_dir = manifest_dir.join("adapters");
    println!("cargo:rerun-if-changed={}", adapters_dir.display());
    let mut manifests = fs::read_dir(&adapters_dir)
        .unwrap_or_else(|error| {
            panic!("无法读取来源适配器目录 {}：{error}", adapters_dir.display())
        })
        .filter_map(Result::ok)
        .filter(|entry| entry.file_type().map(|kind| kind.is_dir()).unwrap_or(false))
        .filter_map(|entry| {
            let package_name = entry.file_name().to_string_lossy().to_string();
            if package_name.starts_with('_') {
                return None;
            }
            let package_root = entry.path();
            let manifest = package_root.join("manifest.json");
            let acceptance = package_root.join("acceptance.json");
            let implementation = package_root.join("adapter.rs");
            manifest.is_file().then_some((
                package_name,
                manifest,
                acceptance.is_file().then_some(acceptance),
                implementation.is_file().then_some(implementation),
            ))
        })
        .collect::<Vec<_>>();
    manifests.sort_by(|left, right| left.0.cmp(&right.0));
    if manifests.is_empty() {
        panic!("来源适配器目录中没有可注册的 manifest.json");
    }
    let mut generated = String::from(
        "// @generated by build.rs; add an adapter directory instead of editing this file.\n\
         const ADAPTER_MANIFESTS: &[(&str, &str)] = &[\n",
    );
    let mut implementation_modules = Vec::new();
    let mut acceptance_contracts = Vec::new();
    for (package_name, manifest, acceptance, implementation) in manifests {
        println!("cargo:rerun-if-changed={}", manifest.display());
        generated.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            package_name,
            manifest.to_string_lossy()
        ));
        if let Some(acceptance) = acceptance {
            println!("cargo:rerun-if-changed={}", acceptance.display());
            acceptance_contracts.push((package_name.clone(), acceptance));
        }
        if let Some(implementation) = implementation {
            println!("cargo:rerun-if-changed={}", implementation.display());
            let module_name = format!(
                "adapter_package_{}",
                package_name
                    .chars()
                    .map(|character| {
                        if character.is_ascii_alphanumeric() {
                            character.to_ascii_lowercase()
                        } else {
                            '_'
                        }
                    })
                    .collect::<String>()
            );
            implementation_modules.push((module_name, implementation));
        }
    }
    generated.push_str("];\n");
    generated.push_str("const ADAPTER_ACCEPTANCE_CONTRACTS: &[(&str, &str)] = &[\n");
    for (package_name, acceptance) in acceptance_contracts {
        generated.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            package_name,
            acceptance.to_string_lossy()
        ));
    }
    generated.push_str("];\n");
    for (module_name, implementation) in &implementation_modules {
        generated.push_str(&format!(
            "#[path = {:?}]\nmod {};\n",
            implementation.to_string_lossy(),
            module_name
        ));
    }
    generated
        .push_str("fn registered_adapter_bindings() -> Vec<SourceAdapterBinding> {\n    vec![\n");
    for (module_name, _) in &implementation_modules {
        generated.push_str(&format!("        {}::binding(),\n", module_name));
    }
    generated.push_str("    ]\n}\n");
    let output = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR"))
        .join("source_adapter_manifests.rs");
    if fs::read_to_string(&output).ok().as_deref() != Some(generated.as_str()) {
        fs::write(&output, generated)
            .unwrap_or_else(|error| panic!("写入来源适配器注册表失败：{error}"));
    }
}

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    generate_source_adapter_registry(&manifest_dir);
    #[cfg(target_os = "macos")]
    {
        let development_driver = manifest_dir.join("resources/oracle/instantclient_19_16");
        println!(
            "cargo:rustc-link-arg=-Wl,-rpath,{}",
            development_driver.display()
        );
        println!(
            "cargo:rustc-link-arg=-Wl,-rpath,@executable_path/../Resources/oracle/instantclient_19_16"
        );
    }
    tauri_build::build()
}
