export const targetFields = [
  {
    key: "naMed",
    label: "医疗物品通用名",
    required: true,
    group: "基本信息",
    hint: "写入 hi_bd_med.na_med",
    aliases: ["DRUG_NAME", "GENERIC_NAME", "YPMC", "药品名称"],
  },
  {
    key: "sdMed",
    label: "物品类型编码",
    required: true,
    group: "基本信息",
    hint: "以当前租户 rbmh.base.med.articleType 实时字典为准",
    aliases: ["DRUG_TYPE", "SD_MED", "YPLX", "物品类型"],
    dictionaryId: "rbmh.base.med.articleType",
  },
  {
    key: "sdDose",
    label: "剂型编码",
    required: true,
    group: "基本信息",
    hint: "需映射为新系统剂型字典编码",
    aliases: ["FORM_CODE", "DOSE_FORM", "JXDM", "剂型"],
    dictionaryId: "rbmh.base.med.doseType",
  },
  {
    key: "unitPre",
    label: "制剂单位",
    required: true,
    group: "基本信息",
    hint: "最小制剂单位，例如片、粒、ml",
    aliases: [
      "PRE_UNIT",
      "MIN_UNIT",
      "UNIT_PRE",
      "YPDW",
      "ZXDW",
      "制剂单位",
      "最小单位",
    ],
  },
  {
    key: "dose",
    label: "制剂剂量",
    required: false,
    group: "基本信息",
    hint: "耗材可不填",
    aliases: ["DOSE", "DOSAGE", "JL", "剂量"],
  },
  {
    key: "unitDose",
    label: "剂量单位",
    required: false,
    group: "基本信息",
    hint: "耗材可不填",
    aliases: ["DOSE_UNIT", "UNIT_DOSE", "JLDW", "剂量单位"],
  },
  {
    key: "spec",
    label: "制剂规格",
    required: false,
    group: "基本信息",
    hint: "为空时自动按剂量生成",
    aliases: ["SPEC", "DRUG_SPEC", "GG", "规格"],
  },
  {
    key: "dftUsage",
    label: "默认给药方法编码",
    required: false,
    group: "用药规则",
    hint: "草药、耗材可不填",
    aliases: ["USAGE_CODE", "DFT_USAGE", "GYFF", "用法"],
    dictionaryId: "rbmh.base.med.usage",
  },
  {
    key: "dftFreq",
    label: "默认频次编码",
    required: false,
    group: "用药规则",
    hint: "新系统字段允许为空；老系统有默认频次时再映射",
    aliases: ["FREQ_CODE", "DFT_FREQ", "PCDM", "频次"],
    dictionaryId: "rbmh.base.freq",
  },
  {
    key: "dftDoseOnce",
    label: "默认一次用量",
    required: false,
    group: "用药规则",
    hint: "原模板“一次用量”，草药未填时使用制剂剂量",
    aliases: ["DOSE_ONCE", "DFT_DOSE_ONCE", "YCJL", "一次用量"],
  },
  {
    key: "sdRound",
    label: "取整策略编码",
    required: false,
    group: "用药规则",
    hint: "需映射为新系统取整策略字典编码",
    aliases: ["ROUND_CODE", "SD_ROUND", "QZCL", "取整策略"],
    dictionaryId: "rbmh.base.med.roundingStrategy",
  },
  {
    key: "sdDps",
    label: "发药方式编码",
    required: false,
    group: "用药规则",
    hint: "需映射为新系统发药方式字典编码",
    aliases: ["DISPENSE_CODE", "SD_DPS", "FYFS", "发药方式"],
    dictionaryId: "rbmh.base.med.dispensingMethod",
  },
  {
    key: "idFac",
    label: "生产厂家主键",
    required: false,
    group: "厂家商品",
    hint: "已有厂家对照时优先使用",
    aliases: ["FACTORY_ID", "ID_FAC", "CJID"],
  },
  {
    key: "naFac",
    label: "生产厂家名称",
    required: false,
    group: "厂家商品",
    hint: "厂家主键为空时用于精确匹配",
    aliases: ["FACTORY_NAME", "MANUFACTURER", "SCCJ", "生产厂家"],
  },
  {
    key: "naFacShort",
    label: "生产厂家简称",
    required: false,
    group: "厂家商品",
    hint: "新建厂家时写入厂家基础表简称",
    aliases: ["FACTORY_SHORT_NAME", "CDMC", "厂家简称"],
  },
  {
    key: "pyFac",
    label: "生产厂家拼音码",
    required: false,
    group: "厂家商品",
    hint: "新建厂家时写入厂家基础表拼音码",
    aliases: ["FACTORY_PINYIN", "FACTORY_PY", "厂家拼音码"],
  },
  {
    key: "naMedPro",
    label: "商品名",
    required: false,
    group: "厂家商品",
    hint: "为空时使用通用名",
    aliases: ["PRODUCT_NAME", "BRAND_NAME", "SPM", "商品名"],
  },
  {
    key: "unitSale",
    label: "零售包装单位",
    required: false,
    group: "包装价格",
    hint: "存在商品信息时必填，例如盒、瓶、支",
    aliases: ["SALE_UNIT", "PACK_UNIT", "UNIT_SALE", "包装单位"],
  },
  {
    key: "unitSaleFactor",
    label: "包装系数",
    required: false,
    group: "包装价格",
    hint: "存在商品信息时必填，必须为正整数",
    aliases: ["PACK_FACTOR", "UNIT_FACTOR", "BZXS", "包装系数"],
  },
  {
    key: "specSale",
    label: "零售包装规格",
    required: false,
    group: "包装价格",
    hint: "为空时自动生成",
    aliases: ["SALE_SPEC", "PACK_SPEC", "SPEC_SALE", "包装规格"],
  },
  {
    key: "pricePur",
    label: "进货价格",
    required: false,
    group: "包装价格",
    hint: "存在商品信息时必填，允许为0，不允许负数",
    aliases: ["BUY_PRICE", "PURCHASE_PRICE", "PRICE_PUR", "进货价"],
  },
  {
    key: "priceSale",
    label: "零售价格",
    required: false,
    group: "包装价格",
    hint: "存在商品信息时必填，允许为0，不允许负数",
    aliases: ["RETAIL_PRICE", "SALE_PRICE", "PRICE_SALE", "零售价"],
  },
  {
    key: "cdAppr",
    label: "批准文号",
    required: false,
    group: "监管编码",
    hint: "药品批准文号",
    aliases: ["APPROVAL_NO", "LICENSE_NO", "CD_APPR", "批准文号"],
  },
  {
    key: "cdBar",
    label: "条形码",
    required: false,
    group: "监管编码",
    hint: "商品条形码",
    aliases: ["BARCODE", "CD_BAR", "条形码"],
  },
  {
    key: "cdMedPro",
    label: "货品码",
    required: false,
    group: "监管编码",
    hint: "三方商品编码",
    aliases: ["DRUG_CODE", "ITEM_CODE", "CD_MED_PRO", "货品码"],
  },
  {
    key: "sdBasMed",
    label: "基药类型编码",
    required: false,
    group: "监管属性",
    hint: "需映射为新系统基药类型字典编码",
    aliases: ["BASIC_DRUG_TYPE", "SD_BAS_MED", "JYLX", "基药类型"],
    dictionaryId: "rbmh.base.med.baseMed",
  },
  {
    key: "fgMedRx",
    label: "处方药标志",
    required: false,
    group: "监管属性",
    hint: "按目标字典转换：1处方药、2非处方药",
    aliases: ["RX_FLAG", "FG_MED_RX", "CFYP", "处方药品"],
    dictionaryId: "rbmh.base.med.prescriptiondrugIdentification",
  },
  {
    key: "sdChrgitmLv",
    label: "医保分类编码",
    required: false,
    group: "监管属性",
    hint: "原模板“医保分类”，按新系统甲乙丙字典接入",
    aliases: ["INSURANCE_LEVEL", "SD_CHRGITM_LV", "YBFL", "医保分类"],
    dictionaryId: "phis.medicareLevel",
  },
  {
    key: "sdStorage",
    label: "药品储藏编码",
    required: false,
    group: "监管属性",
    hint: "需映射为新系统储藏字典编码",
    aliases: ["STORAGE_CODE", "SD_STORAGE", "YPZC", "药品储藏"],
    dictionaryId: "phis.storageType",
  },
  {
    key: "sdSpeMed",
    label: "特殊药品编码",
    required: false,
    group: "监管属性",
    hint: "需映射为新系统特殊药品字典编码",
    aliases: ["SPECIAL_DRUG_TYPE", "SD_SPE_MED", "TSYP", "特殊药品"],
    dictionaryId: "rbmh.base.med.sdSpeMed",
  },
  {
    key: "sdAllergy",
    label: "过敏类别编码",
    required: false,
    group: "用药规则",
    hint: "来自 HiBdMed 的过敏类别标准字典",
    aliases: ["ALLERGY_CODE", "SD_ALLERGY", "GMYWLB", "过敏类别"],
    dictionaryId: "rbmh.base.med.sdAllergy",
  },
  {
    key: "fgAntiAppr",
    label: "抗菌药物审批标志",
    required: false,
    group: "抗菌药物",
    hint: "按新系统是否字典转换为0/1",
    aliases: ["ANTI_APPROVAL", "FG_ANTI_APPR", "SFSP", "抗菌审批"],
    dictionaryId: "sys.sd.yesOrNo",
  },
  {
    key: "sdProdPlac",
    label: "产地类别编码",
    required: false,
    group: "厂家商品",
    hint: "按新系统国产/进口产地类别字典转换",
    aliases: ["ORIGIN_TYPE", "SD_PROD_PLAC", "YPDC", "档次", "产地类别"],
    dictionaryId: "rbmh.base.med.drugGrade",
  },
  {
    key: "fgPois",
    label: "毒麻药品标志",
    required: false,
    group: "监管属性",
    hint: "按新系统是否字典转换为0/1",
    aliases: ["POISON_FLAG", "FG_POIS", "DMBS", "毒麻标志"],
    dictionaryId: "sys.sd.yesOrNo",
  },
  {
    key: "fgAnti",
    label: "抗菌药物标志",
    required: false,
    group: "抗菌药物",
    hint: "按新系统是否字典转换为0/1",
    aliases: ["ANTIBIOTIC_FLAG", "FG_ANTI", "KSBZ", "抗菌标志"],
    dictionaryId: "sys.sd.yesOrNo",
  },
  {
    key: "fgTcd",
    label: "中药饮片标志",
    required: false,
    group: "监管属性",
    hint: "按新系统是否字典转换为0/1",
    aliases: ["TCM_DECOCTION_FLAG", "FG_TCD", "ZYYPBS", "中药饮片"],
    dictionaryId: "sys.sd.yesOrNo",
  },
  {
    key: "fgSingle",
    label: "允许单开标志",
    required: false,
    group: "用药规则",
    hint: "按新系统是否字典转换为0/1",
    aliases: ["SINGLE_FLAG", "FG_SINGLE", "YXDK", "允许单开"],
    dictionaryId: "sys.sd.yesOrNo",
  },
  {
    key: "fgRegister",
    label: "注册证管理标志",
    required: false,
    group: "监管属性",
    hint: "按新系统注册证管理字典转换",
    aliases: ["REGISTER_FLAG", "FG_REGISTER", "ZCZGL", "需要注册"],
    dictionaryId: "phis.ifNeedRegister",
  },
  {
    key: "limitAntiDay",
    label: "一日限量",
    required: false,
    group: "监管属性",
    hint: "不得小于0",
    aliases: ["DAILY_LIMIT", "LIMIT_ANTI_DAY", "YCYL", "一日限量"],
  },
  {
    key: "fgCollPur",
    label: "集采标志",
    required: false,
    group: "商品属性",
    hint: "统一转换为0否、1是",
    aliases: ["COLLECTIVE_PURCHASE", "FG_COLL_PUR", "JCBS", "集采"],
  },
  {
    key: "fgImport",
    label: "进口药品标志",
    required: false,
    group: "商品属性",
    hint: "统一转换为0否、1是",
    aliases: ["IMPORT_FLAG", "FG_IMPORT", "JKYP", "进口药品"],
  },
];

const validationFieldAliases = {
  idFac: ["生产厂家主键"],
  naFac: ["生产厂家名称", "生产厂家主键或名称"],
  fgPois: ["毒性药品标志"],
  limitAntiDay: ["抗菌药物限用天数"],
};

export function fieldsMentionedInValidationError(message = "") {
  if (!message) return [];
  return targetFields.filter((field) => {
    const escapedKey = field.key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const mentionsKey = new RegExp(
      `(^|[^A-Za-z0-9_])${escapedKey}([^A-Za-z0-9_]|$)`,
      "i",
    ).test(message);
    const labels = [field.label, ...(validationFieldAliases[field.key] || [])];
    return mentionsKey || labels.some((label) => message.includes(label));
  });
}

const targetFieldLocations = {
  naMed: ["hi_bd_med.na_med"],
  sdMed: ["hi_bd_med.sd_med"],
  sdDose: ["hi_bd_med.sd_dose"],
  unitPre: ["hi_bd_med.unit_pre"],
  dose: ["hi_bd_med.dose"],
  unitDose: ["hi_bd_med.unit_dose"],
  spec: ["hi_bd_med.spec"],
  dftUsage: ["hi_bd_med.dft_usage"],
  dftFreq: ["hi_bd_med.dft_freq"],
  dftDoseOnce: ["hi_bd_med.dft_dose_once"],
  sdRound: ["hi_bd_med.sd_round"],
  sdDps: ["hi_bd_med.sd_dps"],
  idFac: ["hi_bd_med_pro.id_fac"],
  naFac: ["hi_bd_fac.na_fac", "hi_bd_med_pro.id_fac（关联）"],
  naFacShort: ["hi_bd_fac.na_fac_short"],
  pyFac: ["hi_bd_fac.py"],
  naMedPro: ["hi_bd_med_pro.na_med_pro"],
  unitSale: ["hi_bd_med_pro.unit_sale"],
  unitSaleFactor: ["hi_bd_med_pro.unit_sale_factor"],
  specSale: ["hi_bd_med_pro.spec_sale"],
  pricePur: ["hi_bd_med_pro.price_pur"],
  priceSale: ["hi_bd_med_pro.price_sale"],
  cdAppr: ["hi_bd_med_pro.cd_appr"],
  cdBar: ["hi_bd_med_pro.cd_bar"],
  cdMedPro: ["hi_bd_med_pro.cd_med_pro"],
  sdBasMed: ["hi_bd_med.sd_bas_med"],
  fgMedRx: ["hi_bd_med.fg_med_rx"],
  sdChrgitmLv: ["hi_bd_med.sd_chrgitm_lv"],
  sdStorage: ["hi_bd_med.sd_storage"],
  sdSpeMed: ["hi_bd_med.sd_spe_med"],
  sdAllergy: ["hi_bd_med.sd_allergy"],
  fgAntiAppr: ["hi_bd_med.fg_anti_appr"],
  sdProdPlac: ["hi_bd_med.sd_prod_plac", "hi_bd_fac.sd_prod_plac（新建厂家时）"],
  fgPois: ["hi_bd_med.fg_pois"],
  fgAnti: ["hi_bd_med.fg_anti"],
  fgTcd: ["hi_bd_med.fg_tcd"],
  fgSingle: ["hi_bd_med.fg_single"],
  fgRegister: ["hi_bd_med.fg_register"],
  limitAntiDay: ["hi_bd_med.limit_anti_day"],
  fgCollPur: ["hi_bd_med_pro.fg_coll_pur"],
  fgImport: ["hi_bd_med_pro.fg_import"],
};

export function targetLocations(field) {
  return targetFieldLocations[field?.key] || [];
}

export function targetPhysicalLocationText(field) {
  return targetLocations(field)
    .map((location) => location.replace(/（.*$/, ""))
    .join("、");
}

const booleanTargetFieldKeys = new Set([
  "fgAntiAppr",
  "fgPois",
  "fgAnti",
  "fgTcd",
  "fgSingle",
  "fgRegister",
  "fgCollPur",
  "fgImport",
]);

export function defaultTransformForField(field) {
  return booleanTargetFieldKeys.has(field?.key) ? "BOOLEAN_01" : "TRIM";
}
